# Generated by Django 5.0.14 on 2025-12-09 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voters", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="volunteer",
            options={"ordering": ["level", "volunteer_id"]},
        ),
        migrations.AddField(
            model_name="volunteer",
            name="volunteer_id",
            field=models.IntegerField(
                default=0,
                help_text="Unique ID within the level (e.g., Level 1: 1,2,3... Level 2: 1,2,3...)",
                verbose_name="Volunteer ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="volunteer",
            unique_together={("level", "volunteer_id")},
        ),
        migrations.CreateModel(
            name="AppSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "voting_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enable this on polling day to allow volunteers to mark voters as voted",
                        verbose_name="Enable Voting",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Application Settings",
                "verbose_name_plural": "Application Settings",
                "db_table": "app_settings",
            },
        ),
    ]
